build:
  builder:
    image: clamp/builder:0.2.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t clamp/builder:latest images
  volume-container:
    image: clamp/builder:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t clamp/lib-volume:latest images/lib/volume
      - docker save -o lib-volume clamp/lib-volume:latest
      - docker load -i lib-volume
publish:
  docker:
    username: $$DUSER
    password: $$DPASS
    email: $$DEMAIL
    repo: clamp/builder
    tag: latest
    file: images/Dockerfile
clone:
  path: /build