debug: true
build:
  vol-container:
    image: clamp/builder:0.2.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh lib volume $$BUILD_NUMBER
  base-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh lib base $$BUILD_NUMBER
  mysql-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh lib mysql $$BUILD_NUMBER
  php-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh lib php-7 $$BUILD_NUMBER
  consul-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh lib consul-server $$BUILD_NUMBER
  mysql-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run mysql $$BUILD_NUMBER
  plugin-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run plugin $$BUILD_NUMBER
  wordpress-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run wordpress $$BUILD_NUMBER
  memcached-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run memcached $$BUILD_NUMBER
  nginx-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run nginx $$BUILD_NUMBER
  php-fpm-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run php-fpm $$BUILD_NUMBER
  haproxy-run-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh run haproxy $$BUILD_NUMBER
  plugin-builder-container:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./templated-build.sh srv composer $$BUILD_NUMBER
  tag-release:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker tag clamp/lib-base:$$BUILD_NUMBER clamp/lib-base:$$DOCKER_TAG
      - docker tag clamp/lib-consul-server:$$BUILD_NUMBER clamp/lib-consul-server:$$DOCKER_TAG
      - docker tag clamp/lib-mysql:$$BUILD_NUMBER clamp/lib-mysql:$$DOCKER_TAG
      - docker tag clamp/lib-php-7:$$BUILD_NUMBER clamp/lib-php-7:$$DOCKER_TAG
      - docker tag clamp/lib-volume:$$BUILD_NUMBER clamp/lib-volume:$$DOCKER_TAG
      - docker tag clamp/run-haproxy:$$BUILD_NUMBER clamp/run-haproxy:$$DOCKER_TAG
      - docker tag clamp/run-memcached:$$BUILD_NUMBER clamp/run-memcached:$$DOCKER_TAG
      - docker tag clamp/run-mysql:$$BUILD_NUMBER clamp/run-mysql:$$DOCKER_TAG
      - docker tag clamp/run-nginx:$$BUILD_NUMBER clamp/run-nginx:$$DOCKER_TAG
      - docker tag clamp/run-php-fpm:$$BUILD_NUMBER clamp/run-php-fpm:$$DOCKER_TAG
      - docker tag clamp/run-plugin:$$BUILD_NUMBER clamp/run-plugin:$$DOCKER_TAG
      - docker tag clamp/run-wordpress:$$BUILD_NUMBER clamp/run-wordpress:$$DOCKER_TAG
      - docker tag clamp/srv-composer:$$BUILD_NUMBER clamp/run-composer:$$DOCKER_TAG
      - docker tag clamp/lib-base:$$BUILD_NUMBER clamp/lib-base:$$DOCKER_TAG
    when:
      event: tag
      matrix:
        DOCKER_TAG: [latest, $$TAG]
  tag-pr:
    image: clamp/builder:0.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker tag clamp/lib-base:$$BUILD_NUMBER clamp/lib-base:$$DOCKER_TAG
      - docker tag clamp/lib-consul-server:$$BUILD_NUMBER clamp/lib-consul-server:$$DOCKER_TAG
      - docker tag clamp/lib-mysql:$$BUILD_NUMBER clamp/lib-mysql:$$DOCKER_TAG
      - docker tag clamp/lib-php-7:$$BUILD_NUMBER clamp/lib-php-7:$$DOCKER_TAG
      - docker tag clamp/lib-volume:$$BUILD_NUMBER clamp/lib-volume:$$DOCKER_TAG
      - docker tag clamp/run-haproxy:$$BUILD_NUMBER clamp/run-haproxy:$$DOCKER_TAG
      - docker tag clamp/run-memcached:$$BUILD_NUMBER clamp/run-memcached:$$DOCKER_TAG
      - docker tag clamp/run-mysql:$$BUILD_NUMBER clamp/run-mysql:$$DOCKER_TAG
      - docker tag clamp/run-nginx:$$BUILD_NUMBER clamp/run-nginx:$$DOCKER_TAG
      - docker tag clamp/run-php-fpm:$$BUILD_NUMBER clamp/run-php-fpm:$$DOCKER_TAG
      - docker tag clamp/run-plugin:$$BUILD_NUMBER clamp/run-plugin:$$DOCKER_TAG
      - docker tag clamp/run-wordpress:$$BUILD_NUMBER clamp/run-wordpress:$$DOCKER_TAG
      - docker tag clamp/srv-composer:$$BUILD_NUMBER clamp/run-composer:$$DOCKER_TAG
      - docker tag clamp/lib-base:$$BUILD_NUMBER clamp/lib-base:$$DOCKER_TAG
    when:
      event: pull_request
      matrix:
        DOCKER_TAG: [$${BRANCH///-}]
publish:
  docker:
    username: $$DUSER
    password: $$DPASS
    email: $$DEMAIL
    repo: clamp/lib-volume
    tag: $$BUILD_NUMBER
    when:
      event: [pull_request]
matrix:
  DOCKER_TAG:
    - $$BUILD_NUMBER
    - $${BRANCH///-}
    - latest
    - $$TAG
clone:
  path: /build