build:
  builder:
    image: clamp/builder:0.2.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t clamp/builder:latest images
publish:
  docker:
    username: $$DUSER
    password: $$DPASS
    email: $$DEMAIL
    repo: clamp/builder
    tag: latest
    file: images/Dockerfile
clone:
  path: /build