build:
  bases:
    image: clamp/lib-base
    pull: true
    commands:
      - images/build.all --bases
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VERSION=0.2
clone:
  path: /build