wordpress:
  build: images/wordpress
  volumes_from:
    - akismet
php-apache:
  build: images/apache
  volumes_from:
    - wordpress
  ports:
    - "80:80"
  links:
    - "db:db"
    - "db_slave:db_slave"
  environment:
    DB_NAME: "wordpress"
    DB_USER: "admin"
    DB_PASSWORD: "password"
    DB_HOST: "1234"
    WP_ENV: "development"
    WP_HOME: "http://192.168.99.100"
    WP_SITE_URL: "http://192.168.99.100"
    AUTH_KEY: ""
    SECURE_AUTH_KEY: ""
    LOGGED_IN_KEY: ""
    NONCE_KEY: ""
    AUTH_SALT: ""
    SECURE_AUTH_SALT: ""
    LOGGED_IN_SALT: ""
    NONCE_SALT: ""
db-data:
  image: ubuntu:14.04
  volumes:
    - /var/lib/mysql
db:
  build: images/mysql
  volumes_from:
    - db-data
  environment:
    ON_CREATE_DB: "wordpress"
    REPLICATION_MASTER: "true"
    REPLICATION_PASS: "replica"
    MYSQL_PASS: "password"
  ports:
    - "3306:3306"
db_slave:
  build: images/mysql
  environment:
    ON_CREATE_DB: "wordpress"
    REPLICATION_SLAVE: "true"
    REPLICATION_PASS: "replica"
    MYSQL_PASS: "password"
  links:
    - "db:mysql"
  ports:
    - "3307:3307"
akismet:
  image: clamp/plugin-captcha:latest