php-apache:
  image: clamp/run-apache:latest
  volumes_from:
    - wordpress
  ports:
    - "80:80"
  links:
    - "db:db"
    - "db_slave:db_slave"
    - "memcached:memcached_cluster"
  environment:
    DB_NAME: "wordpress"
    DB_USER: "admin"
    DB_PASSWORD: "password"
    DB_HOST: "1234"
    WP_ENV: "development"
    WP_HOME: "http://192.168.99.100"
    WP_SITE_URL: "http://192.168.99.100"
    AUTH_KEY: ""
    SECURE_AUTH_KEY: ""
    LOGGED_IN_KEY: ""
    NONCE_KEY: ""
    AUTH_SALT: ""
    SECURE_AUTH_SALT: ""
    LOGGED_IN_SALT: ""
    NONCE_SALT: ""
memcached:
  image: clamp/run-memcached:latest
db-data:
  image: ubuntu:14.04
db:
  image: clamp/run-mysql:latest
  volumes_from:
    - db-data
  environment:
    ON_CREATE_DB: "wordpress"
    REPLICATION_MASTER: "true"
    REPLICATION_PASS: "replica"
    MYSQL_PASS: "password"
  ports:
    - "3306:3306"
db_slave:
  image: clamp/run-mysql:latest
  environment:
    ON_CREATE_DB: "wordpress"
    REPLICATION_SLAVE: "true"
    REPLICATION_PASS: "replica"
    MYSQL_PASS: "password"
  links:
    - "db:mysql"
  ports:
    - "3307:3307"
uploads:
  image: ubuntu:14.04
  volumes:
    - ./data:/var/www/html/app/uploads
wordpress:
  image: clamp/run-wordpress:latest
  volumes:
    - ./images/wordpress/root/var/www/html:/var/www/html
  volumes_from:
    - uploads
    # Add plugins below
    - akismet
    - application-insights
    - crayon-syntax-highlighter
    - disable-responsive-images
    - google-analytics-for-wordpress
    - jetpack
    - sendgrid-email-delivery-simplified
    # End plugins
akismet:
  image: clamp/plugin-akismet:latest
application-insights:
  image: clamp/plugin-application-insights:latest
crayon-syntax-highlighter:
  image: clamp/plugin-crayon-syntax-highlighter:latest
disable-responsive-images:
  image: clamp/plugin-disable-responsive-images:latest
google-analytics-for-wordpress:
  image: clamp/plugin-google-analytics-for-wordpress:latest
jetpack:
  image: clamp/plugin-jetpack:latest
sendgrid-email-delivery-simplified:
  image: clamp/plugin-sendgrid-email-delivery-simplified